-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accounts
(
    id bigint NOT NULL DEFAULT nextval('accounts_account_id_seq'::regclass),
    uye_id integer NOT NULL,
    hesap_tur integer NOT NULL,
    para_tur integer NOT NULL,
    balance integer,
    CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bank
(
    "kullanıcı_kodu" integer NOT NULL DEFAULT nextval('branchs_branch_id_seq'::regclass),
    "üye_ismi" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT branchs_pkey PRIMARY KEY ("kullanıcı_kodu")
);

CREATE TABLE IF NOT EXISTS public.workers
(
    id integer NOT NULL DEFAULT nextval('customers_customer_id_seq'::regclass),
    "kullanıcı_kodu" integer NOT NULL,
    isim character varying COLLATE pg_catalog."default" NOT NULL,
    soy_isim character varying COLLATE pg_catalog."default" NOT NULL,
    adres character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying NOT NULL,
    telefon bigint NOT NULL,
    tc bigint NOT NULL,
    "maaş" bigint,
    sifre character varying NOT NULL,
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.acc_tur
(
    "tür_id" bigint NOT NULL DEFAULT nextval('loans_loan_id_seq'::regclass),
    hesap_ismi integer NOT NULL,
    PRIMARY KEY ("tür_id")
);

CREATE TABLE IF NOT EXISTS public.yat_fon
(
    para_id bigint NOT NULL DEFAULT nextval('transactions_transaction_id_seq'::regclass),
    para_ismi character varying COLLATE pg_catalog."default" NOT NULL,
    kur bigint,
    CONSTRAINT transactions_pkey PRIMARY KEY (para_id)
);

CREATE TABLE IF NOT EXISTS public.cus_list
(
    id bigint NOT NULL,
    isim character varying NOT NULL,
    soy_isim character varying NOT NULL,
    adres character varying NOT NULL,
    email character varying NOT NULL,
    telefon bigint NOT NULL,
    tc bigint NOT NULL,
    temsilci_id bigint NOT NULL,
    sifre character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sistem
(
    tarih date,
    id integer NOT NULL,
    tc bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.islem
(
    islem_no bigint NOT NULL,
    islem character varying NOT NULL,
    kaynak bigint,
    hedef bigint,
    tutar bigint NOT NULL,
    kaynak_bakiye bigint,
    hedef_bakiye bigint,
    tarih date NOT NULL,
    PRIMARY KEY (islem_no)
);

CREATE TABLE IF NOT EXISTS public.kredi_talep
(
    kredi_id bigint NOT NULL,
    uye_id bigint NOT NULL,
    talep_miktar bigint NOT NULL,
    onay character varying NOT NULL,
    PRIMARY KEY (uye_id)
);

CREATE TABLE IF NOT EXISTS public.kredi_islem
(
    id bigint NOT NULL,
    kredi_tur character varying NOT NULL,
    vade bigint NOT NULL,
    faiz bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.accounts
    ADD FOREIGN KEY (uye_id)
    REFERENCES public.cus_list (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.accounts
    ADD FOREIGN KEY (hesap_tur)
    REFERENCES public.acc_tur ("tür_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.accounts
    ADD FOREIGN KEY (para_tur)
    REFERENCES public.yat_fon (para_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.workers
    ADD FOREIGN KEY ("kullanıcı_kodu")
    REFERENCES public.bank ("kullanıcı_kodu") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cus_list
    ADD FOREIGN KEY (temsilci_id)
    REFERENCES public.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sistem
    ADD FOREIGN KEY (tc)
    REFERENCES public.workers (tc) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.islem
    ADD FOREIGN KEY (tarih)
    REFERENCES public.sistem (tarih) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;